'use client';

import { ChefHat, Clock3, CheckCircle2 } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';

const orders = [{ id: '#1048', table: 'Table 12', status: 'Preparing', time: '8 min', items: ['Truffle pasta', 'Garden bowl'] }, { id: '#1049', table: 'Table 08', status: 'Pending', time: '3 min', items: ['Crispy chicken', 'Sparkling water'] }, { id: '#1044', table: 'Table 18', status: 'Ready', time: '2 min', items: ['Chocolate torte', 'Espresso'] }];
export default function KitchenDashboardPage() { return <div className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl space-y-8"><header className="flex items-center justify-between"><div><p className="flex items-center gap-2 text-sm font-semibold text-emerald-600"><ChefHat className="h-4 w-4" /> Kitchen operations</p><h1 className="page-heading mt-1">Service board</h1><p className="page-subheading">Keep every plate moving with a clear view of the pass.</p></div><Badge tone="green"><span className="mr-1 h-2 w-2 rounded-full bg-emerald-500" /> Live</Badge></header><div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-sm text-slate-500">Incoming</p><p className="mt-2 text-3xl font-bold">1</p></Card><Card><p className="text-sm text-slate-500">Preparing</p><p className="mt-2 text-3xl font-bold">1</p></Card><Card><p className="text-sm text-slate-500">Ready to run</p><p className="mt-2 text-3xl font-bold">1</p></Card></div><div className="grid gap-4 lg:grid-cols-3">{orders.map(order => <Card key={order.id} className="border-t-4 border-t-emerald-500"><div className="flex items-center justify-between"><div><p className="text-lg font-bold">{order.id}</p><p className="text-sm text-slate-500">{order.table}</p></div><Badge tone={order.status === 'Ready' ? 'green' : order.status === 'Preparing' ? 'amber' : 'blue'}>{order.status}</Badge></div><div className="mt-6 space-y-2">{order.items.map(item => <div key={item} className="flex items-center gap-2 text-sm font-medium"><CheckCircle2 className="h-4 w-4 text-emerald-500" />{item}</div>)}</div><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-4"><span className="flex items-center gap-1 text-xs text-slate-400"><Clock3 className="h-3.5 w-3.5" /> {order.time}</span><Button size="sm" variant={order.status === 'Ready' ? 'secondary' : 'primary'}>{order.status === 'Pending' ? 'Start preparing' : order.status === 'Preparing' ? 'Mark ready' : 'Mark served'}</Button></div></Card>)}</div></div></div>; }
