'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api';
import { Activity, ArrowRight, CalendarCheck, ChefHat, ClipboardList, Clock3, Heart, LineChart, RefreshCw, Shield, Sparkles, UtensilsCrossed } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';

const features = [
  { icon: CalendarCheck, title: 'QR table booking', text: 'Let guests reserve a table in seconds, from any device.' },
  { icon: Clock3, title: 'Dynamic queue', text: 'Turn waiting time into a clear, calm guest experience.' },
  { icon: UtensilsCrossed, title: 'Digital menu', text: 'Keep menus current and orders moving without friction.' },
  { icon: ChefHat, title: 'Kitchen sync', text: 'Give every order a clear path from table to kitchen.' },
  { icon: Heart, title: 'Guest loyalty', text: 'Build the relationships that bring people back.' },
  { icon: LineChart, title: 'Useful analytics', text: 'See what is working across service, sales, and demand.' },
];

export default function LandingPage() {
  const [health, setHealth] = useState<'checking' | 'online' | 'offline'>('checking');
  const checkHealth = async () => { setHealth('checking'); try { await apiFetch('/api/health'); setHealth('online'); } catch { setHealth('offline'); } };
  useEffect(() => { checkHealth(); }, []);
  return <main className="min-h-screen overflow-hidden bg-slate-50 text-slate-900">
    <section className="relative border-b border-slate-200 bg-white"><div className="absolute right-0 top-0 h-full w-1/3 bg-amber-50/70 [clip-path:polygon(35%_0,100%_0,100%_100%,0_100%)]" /><div className="relative mx-auto max-w-7xl px-6 pb-20 pt-7 lg:px-10"><nav className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3 font-bold"><span className="rounded-xl bg-amber-500 p-2 text-white"><UtensilsCrossed className="h-5 w-5" /></span><span>Smart Dining</span></Link><div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-semibold text-slate-600 sm:block">Owner login</Link><Link href="/admin-login" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Admin portal</Link></div></nav><div className="grid items-center gap-12 pt-20 lg:grid-cols-[1.05fr_.95fr]"><div><Badge tone="amber"><Sparkles className="mr-1 h-3.5 w-3.5" /> One platform, every service moment</Badge><h1 className="mt-6 max-w-2xl text-5xl font-bold leading-[1.05] tracking-tight text-slate-900 sm:text-6xl">From reservation to <span className="text-amber-500">delicious experience.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Smart Dining brings bookings, queues, menus, kitchens, and insights into one connected platform for modern restaurants.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/book/rest-1" className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-5 py-3.5 font-semibold text-white shadow-lg shadow-amber-500/20 hover:bg-amber-600">Book a table <ArrowRight className="h-4 w-4" /></Link><Link href="/login" className="rounded-xl border border-slate-200 bg-white px-5 py-3.5 font-semibold text-slate-700 hover:bg-slate-50">Run your restaurant</Link></div></div><div className="relative"><div className="rounded-[2rem] border border-amber-100 bg-gradient-to-br from-amber-100 via-white to-sky-50 p-5 shadow-xl shadow-slate-200/60"><div className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center justify-between"><span className="text-sm text-slate-300">Tonight at a glance</span><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /></div><p className="mt-8 text-4xl font-bold">128 <span className="text-base font-medium text-slate-400">guests served</span></p><div className="mt-8 grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/10 p-3"><p className="text-xs text-slate-400">Tables</p><p className="mt-1 font-bold">18 / 24</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-xs text-slate-400">Queue</p><p className="mt-1 font-bold">06 min</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-xs text-slate-400">Orders</p><p className="mt-1 font-bold">42</p></div></div></div></div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-amber-600">Everything connected</p><h2 className="mt-3 text-3xl font-bold tracking-tight">A calmer operation, a better table.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="w-fit rounded-xl bg-slate-100 p-3 text-slate-700"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></section>
    <section className="bg-slate-900 px-6 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-amber-400">Choose your path</p><h2 className="mt-3 text-3xl font-bold">The right view for every role.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ href:'/book/rest-1', icon:CalendarCheck, title:"I'm a Customer", text:'Book, browse, order, and enjoy the flow.', tone:'sky'}, { href:'/login', icon:ClipboardList, title:'Restaurant Owner Login', text:'Run service with clarity from one console.', tone:'amber'}, { href:'/admin-login', icon:Shield, title:'Super Admin Login', text:'Keep the whole platform healthy and accountable.', tone:'indigo'}].map(({href, icon:Icon, title, text, tone}) => <Link key={title} href={href} className="group rounded-2xl border border-white/10 bg-white/5 p-6 hover:bg-white/10"><Icon className={`h-6 w-6 ${tone === 'sky' ? 'text-sky-400' : tone === 'amber' ? 'text-amber-400' : 'text-indigo-400'}`} /><h3 className="mt-6 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p><ArrowRight className="mt-6 h-4 w-4 text-slate-500 transition group-hover:translate-x-1 group-hover:text-white" /></Link>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 text-xs text-slate-500 lg:px-10"><span>Smart Dining System</span><button onClick={checkHealth} className="flex items-center gap-2 hover:text-slate-900"><Activity className="h-3.5 w-3.5" /><span>Backend {health === 'checking' ? 'checking' : health === 'online' ? 'online' : 'offline'}</span><RefreshCw className={`h-3 w-3 ${health === 'checking' ? 'animate-spin' : ''}`} /></button></footer>
  </main>;
}
