'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { getCookie, getStoredUser, clearAuthToken } from '@/lib/api';
import { Building2, ClipboardList, LayoutDashboard, LogOut, Loader2, Menu, ShieldCheck, X } from 'lucide-react';

const adminNav = [{ name: 'Restaurants', href: '/restaurants', icon: Building2 }, { name: 'Audit log', href: '/audit-log', icon: ClipboardList }];
export default function SuperAdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [user, setUser] = useState<any>(null); const [checking, setChecking] = useState(true); const [open, setOpen] = useState(false);
  useEffect(() => { const token = getCookie('auth_token') || getCookie('token'); const stored = getStoredUser(); if (!token || !stored || stored.role !== 'super_admin') { clearAuthToken(); router.push('/admin-login'); } else { setUser(stored); setChecking(false); } }, [router]);
  if (checking) return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-7 w-7 animate-spin text-indigo-500" /></div>;
  const signOut = () => { clearAuthToken(); router.push('/admin-login'); };
  return <div className="portal-shell flex"><button aria-label="Open navigation" onClick={() => setOpen(!open)} className="fixed left-4 top-4 z-50 rounded-xl bg-white p-2.5 shadow-md lg:hidden">{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button>{open && <div onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-slate-900/20 lg:hidden" />}<aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-slate-200 bg-white transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center gap-3 border-b border-slate-100 px-6 py-5"><div className="rounded-xl bg-indigo-500 p-2.5 text-white"><ShieldCheck className="h-5 w-5" /></div><div><p className="font-bold">Platform control</p><p className="text-xs text-indigo-600">Super admin</p></div></div><nav className="flex-1 space-y-1 p-4">{adminNav.map(({ name, href, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${pathname === href ? 'bg-indigo-50 text-indigo-700' : 'text-slate-500 hover:bg-slate-50'}`}><Icon className="h-4 w-4" />{name}</Link>)}</nav><div className="border-t border-slate-100 p-4"><button onClick={signOut} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-500 hover:bg-red-50 hover:text-red-600"><LogOut className="h-4 w-4" /> Sign out</button></div></aside><main className="min-w-0 flex-1"><header className="flex h-20 items-center justify-end border-b border-slate-200 bg-white px-6 lg:px-10"><div className="text-right"><p className="text-sm font-semibold">{user?.name || 'Super Admin'}</p><p className="text-xs text-slate-500">{user?.email || 'Platform administrator'}</p></div><div className="ml-3 rounded-full bg-indigo-100 px-3 py-2 text-sm font-bold text-indigo-700">SA</div></header><div className="p-5 sm:p-8 lg:p-10">{children}</div></main></div>;
}
